local style = require "core.style"
local common = require "core.common"

style.background = { common.color "#303446" }
style.background2 = { common.color "#292c3c" }
style.background3 = { common.color "#414559" }
style.text = { common.color "#c6d0f5" }
style.caret = { common.color "#f2d5cf" }
style.accent = { common.color "#ca9ee6" }
style.dim = { common.color "#b5bfe2" }
style.divider = { common.color "#ca9ee6" }
style.selection = { common.color "#626880" }
style.line_number = { common.color "#737994" }
style.line_number2 = { common.color "#ca9ee6" }
style.line_highlight = { common.color "#414559" }
style.scrollbar = { common.color "#626880" }
style.scrollbar2 = { common.color "#737994" }
style.scrollbar_track = { common.color "#292c3c" }

style.syntax["normal"] = { common.color "#e78284" }
style.syntax["symbol"] = { common.color "#babbf1" }
style.syntax["comment"] = { common.color "#737994" }
style.syntax["keyword"] = { common.color "#e78284" }
style.syntax["keyword2"] = { common.color "#e78284" }
style.syntax["number"] = { common.color "#ef9f76" }
style.syntax["literal"] = { common.color "#babbf1" }
style.syntax["string"] = { common.color "#a6d189" }
style.syntax["operator"] = { common.color "#99d1db" }
style.syntax["function"] = { common.color "#8caaee" }
