local style = require "core.style"
local common = require "core.common"
style.background = { common.color "#1e1e2e" } -- base
style.background2 = { common.color "#181825" } -- mantle
style.background3 = { common.color "#313244" } -- surface0
style.text = { common.color "#cdd6f4" } -- text
style.caret = { common.color "#f5e0dc" } -- rosewater
style.accent = { common.color "#cba6f7" } -- mauve
style.dim = { common.color "#bac2de" } -- subtext1
style.divider = { common.color "#cba6f7" } -- mauve
style.selection = { common.color "#585b70" } -- surface2
style.line_number = { common.color "#6c7086" } -- overlay0
style.line_number2 = { common.color "#cba6f7" } -- mauve
style.line_highlight = { common.color "#313244" } -- surface0
style.scrollbar = { common.color "#585b70" } -- surface2
style.scrollbar2 = { common.color "#6c7086" } -- overlay0
style.scrollbar_track = { common.color "#181825" } -- mantle

style.syntax["normal"] = { common.color "#f38ba8" } -- red
style.syntax["symbol"] = { common.color "#b4befe" } -- lavender
style.syntax["comment"] = { common.color "#6c7086" } -- overlay0
style.syntax["keyword"] = { common.color "#f38ba8" } -- red
style.syntax["keyword2"] = { common.color "#f38ba8" } -- red
style.syntax["number"] = { common.color "#fab387" } -- peach
style.syntax["literal"] = { common.color "#b4befe" } -- lavender
style.syntax["string"] = { common.color "#a6e3a1" } -- green
style.syntax["operator"] = { common.color "#89dceb" } -- sky
style.syntax["function"] = { common.color "#89b4fa" } -- blue
