local style = require "core.style"
local common = require "core.common"

style.background = { common.color "#eff1f5" }
style.background2 = { common.color "#e6e9ef" }
style.background3 = { common.color "#ccd0da" }
style.text = { common.color "#4c4f69" }
style.caret = { common.color "#dc8a78" }
style.accent = { common.color "#8839ef" }
style.dim = { common.color "#5c5f77" }
style.divider = { common.color "#8839ef" }
style.selection = { common.color "#bcc0cc" } -- surface1
style.line_number = { common.color "#9ca0b0" }
style.line_number2 = { common.color "#8839ef" }
style.line_highlight = { common.color "#dce0e8" } -- crust
style.scrollbar = { common.color "#acb0be" }
style.scrollbar2 = { common.color "#9ca0b0" }
style.scrollbar_track = { common.color "#dce0e8" } -- crust

style.syntax["normal"] = { common.color "#d20f39" }
style.syntax["symbol"] = { common.color "#7287fd" }
style.syntax["comment"] = { common.color "#9ca0b0" }
style.syntax["keyword"] = { common.color "#d20f39" }
style.syntax["keyword2"] = { common.color "#d20f39" }
style.syntax["number"] = { common.color "#fe640b" }
style.syntax["literal"] = { common.color "#7287fd" }
style.syntax["string"] = { common.color "#40a02b" }
style.syntax["operator"] = { common.color "#04a5e5" }
style.syntax["function"] = { common.color "#1e66f5" }
